//! Regenerate atomsplit's committed classify tables:
//!   cargo run -p bitmap_gen [-- <out_path>]
//! Default `out_path` = ../atomsplit/src/atom_tables.rs. `generate_atom_tables` self-validates every
//! codepoint against the reference `atom()`, so an inconsistent scheme change fails HERE, not at ship.
fn main() {
    let default = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../atomsplit/src/atom_tables.rs"
    );
    let out = std::env::args()
        .nth(1)
        .unwrap_or_else(|| default.to_string());
    std::fs::write(&out, bitmap_gen::generate_atom_tables()).expect("write atom_tables.rs");
    eprintln!("bitmap_gen: wrote {out}");
    // NFD-check scheme (see `atomsplit::nfd::check_tag` for the tag semantics) — derived from
    // atomsplit's committed normalization tables, so it regenerates alongside them.
    let check_out = out.replace("atom_tables.rs", "nfd_check_tables.rs");
    let mut src = bitmap_gen::generate_tables("NFD_CHECK_TABLES", "nfdcheck", &atomsplit::nfd::check_tag);
    src.insert_str(
        0,
        "//! GENERATED by `bitmap_gen` — do NOT edit. NFD-check classify tables (tag semantics in\n         //! `nfd::check_tag`). Regenerate with `cargo run -p bitmap_gen`.\n",
    );
    std::fs::write(&check_out, src).expect("write nfd_check_tables.rs");
    eprintln!("bitmap_gen: wrote {check_out}");
}
