//! Normalization classifier — the [`NormClass`] [`TagScheme`]. Its per-codepoint `u8` is a *bitmask*
//! ([`bit`]) of the properties the normalizers branch on; `INERT == 0` means unchanged by every rule.
//! Fed to [`crate::classify::classify`] (SIMD) / [`crate::classify::classify_scalar`] (scalar) it tags a
//! whole buffer in one pass, so a normalizer can copy inert runs verbatim and touch only flagged chars.
//!
//! Tables are the committed [`NORM_TABLES`](crate::norm_tables), regenerated by `bitmap_gen`'s `norm_tag`
//! from the SAME crates the tk-encode normalizers use at runtime — so a char is inert here IFF the legacy
//! path leaves it unchanged. KEEP [`bit`] IN SYNC with `bitmap_gen::norm_bit`.

/// Per-codepoint normalization property bits; a tag is their OR. `INERT` (`0`) = unchanged by every
/// normalization rule. Real tags are `0..=0x7D`; bit 7 is reserved (the engine's `CONT`/`MB` sentinels),
/// so `norm_tag` never sets it.
pub mod bit {
    /// canonical decomposition changes the char (NFD/NFKD/NFC/NFKC; bert `strip_accents` runs NFD).
    pub const NFD: u8 = 1 << 0;
    /// NFD-stable but *compatibility* decomposition changes it (extends NFKD/NFKC over NFD).
    pub const NFKD: u8 = 1 << 1;
    /// combining mark (`is_combining_mark`, a superset of Mn) — `StripAccents` removes these; bert
    /// `strip_accents` refines to nonspacing marks (Mn) at runtime.
    pub const MARK: u8 = 1 << 2;
    /// has a lowercase mapping (`Lowercase`, bert lowercase).
    pub const LOWER: u8 = 1 << 3;
    /// CJK ideograph — bert `handle_chinese_chars` puts spaces around it.
    pub const CJK: u8 = 1 << 4;
    /// bert `clean_text` removes it (NUL, U+FFFD, control).
    pub const CTRL: u8 = 1 << 5;
    /// whitespace that bert `clean_text` folds to `' '` — EXCLUDING a plain space (which is unchanged,
    /// so it stays inert/borrowable). Also relevant to `Strip`.
    pub const WS: u8 = 1 << 6;
    /// unchanged by every normalization rule → copy verbatim.
    pub const INERT: u8 = 0;
}

/// Continuation / unresolved-multibyte sentinels for this scheme. Bit 7 set → outside the
/// `0..=0x7D` real-tag range (`norm_tag` never sets bit 7), so they never collide with a real tag.
pub const CONT: u8 = 0x81;
pub const MB: u8 = 0x80;

/// Classify `text` into `tags` under the normalization scheme (bitmask tags from [`bit`]).
///
/// Runs the same SIMD/scalar engine as pretok [`crate::classify::classify`], but over
/// [`NORM_TABLES`](crate::norm_tables) with the norm sentinels and no CJK lead-byte shortcut —
/// Hangul syllables and CJK compatibility ideographs decompose under NFD, so the CJK block is not
/// one uniform tag and is resolved via the per-block tables.
#[inline]
pub fn classify(text: &[u8], tags: &mut [u8]) {
    crate::classify::classify_with::<CONT, MB, { crate::classify::NO_CJK }>(
        text,
        tags,
        &crate::norm_tables::NORM_TABLES,
    )
}

#[cfg(test)]
mod tests {
    /// The norm SIMD kernel must be byte-exact with the scalar walk over the same `NORM_TABLES` —
    /// the same guarantee the `Atom` parity test gives the pretok path. Corpus spans every code path:
    /// ASCII, Latin accents (NFD), ligature/fullwidth (NFKD), combining marks, case, CJK Han + Hangul
    /// + Kana (the no-shortcut CJK path), controls, and an astral 4-byte codepoint.
    #[test]
    fn norm_simd_scalar_parity() {
        let corpus = "Hello, world! café ﬁ ² Ａ e\u{0301} ΆΩ Привет مرحبا 中文测试 한글 かなカナ \0\u{7f}\u{feff} 😀𝔘";
        let b = corpus.as_bytes();
        let mut simd = vec![0u8; b.len()];
        let mut scalar = vec![0u8; b.len()];
        super::classify(b, &mut simd);
        crate::classify::classify_scalar_with::<{ super::CONT }>(
            b,
            &mut scalar,
            &crate::norm_tables::NORM_TABLES,
        );
        assert_eq!(simd, scalar, "norm SIMD kernel diverged from the scalar walk");
    }
}
