//! Normalization classifier — the [`NormClass`] [`TagScheme`]. Its per-codepoint `u8` is a *bitmask*
//! ([`bit`]) of the properties the normalizers branch on; `INERT == 0` means unchanged by every rule.
//! Fed to [`crate::classify::classify`] (SIMD) / [`crate::classify::classify_scalar`] (scalar) it tags a
//! whole buffer in one pass, so a normalizer can copy inert runs verbatim and touch only flagged chars.
//!
//! Tables are the committed [`NORM_TABLES`](crate::norm_tables), regenerated by `bitmap_gen`'s `norm_tag`
//! from the SAME crates the tk-encode normalizers use at runtime — so a char is inert here IFF the legacy
//! path leaves it unchanged. KEEP [`bit`] IN SYNC with `bitmap_gen::norm_bit`.

use crate::classify::TagScheme;
use crate::simd_classify::Tables;

/// Per-codepoint normalization property bits; a tag is their OR. `INERT` (`0`) = unchanged by every
/// normalization rule. Real tags are `0..=0x7D`; bit 7 is reserved (the engine's `CONT`/`MB` sentinels),
/// so `norm_tag` never sets it.
pub mod bit {
    /// canonical decomposition changes the char (NFD/NFKD/NFC/NFKC; bert `strip_accents` runs NFD).
    pub const NFD: u8 = 1 << 0;
    /// NFD-stable but *compatibility* decomposition changes it (extends NFKD/NFKC over NFD).
    pub const NFKD: u8 = 1 << 1;
    /// combining mark (`is_combining_mark`, a superset of Mn) — `StripAccents` removes these; bert
    /// `strip_accents` refines to nonspacing marks (Mn) at runtime.
    pub const MARK: u8 = 1 << 2;
    /// has a lowercase mapping (`Lowercase`, bert lowercase).
    pub const LOWER: u8 = 1 << 3;
    /// CJK ideograph — bert `handle_chinese_chars` puts spaces around it.
    pub const CJK: u8 = 1 << 4;
    /// bert `clean_text` removes it (NUL, U+FFFD, control).
    pub const CTRL: u8 = 1 << 5;
    /// whitespace that bert `clean_text` folds to `' '` — EXCLUDING a plain space (which is unchanged,
    /// so it stays inert/borrowable). Also relevant to `Strip`.
    pub const WS: u8 = 1 << 6;
    /// unchanged by every normalization rule → copy verbatim.
    pub const INERT: u8 = 0;
}

/// The normalization tag scheme. Zero-sized; carries the tables via its impl.
pub struct NormClass;

impl TagScheme for NormClass {
    // The norm consumer reads raw bitmask tags and dispatches on set bits — it does NOT go through the
    // atom FSM's 16-entry vqtbl remap — so N_TAGS is the bitmask cardinality, not a vqtbl bound.
    const N_TAGS: usize = 128;
    // Sentinels with bit 7 set, outside the `0..=0x7D` real-tag range (`norm_tag` never sets bit 7).
    const CONT: u8 = 0x81;
    const MB: u8 = 0x80;
    // Hangul syllables and CJK compatibility ideographs (E-lead range) decompose under NFD, so the CJK
    // block is NOT one uniform tag → resolve via the per-block tables, no lead-byte range shortcut.
    const CJK_RANGE_TAG: Option<u8> = None;

    #[inline]
    fn classify_char(text: &[u8], i: usize) -> u8 {
        crate::norm_tables::NORM_TABLES.classify_char(text, i)
    }

    fn tables() -> &'static Tables {
        &crate::norm_tables::NORM_TABLES
    }
}
