from _typeshed import Incomplete
from collections.abc import Sequence
from tokenizers.decoders import Decoder
from tokenizers.models import Model
from tokenizers.normalizers import Normalizer
from tokenizers.pre_tokenizers import PreTokenizer
from tokenizers.processors import PostProcessor
from tokenizers.trainers import Trainer
from typing import Any, Final, final
__version__: Final[str]

@final
class AddedToken:
    def __eq__(self, /, other: AddedToken) -> bool: ...
    def __ge__(self, /, other: AddedToken) -> bool: ...
    def __getstate__(self, /) -> dict: ...
    def __gt__(self, /, other: AddedToken) -> bool: ...
    def __hash__(self, /) -> int: ...
    def __le__(self, /, other: AddedToken) -> bool: ...
    def __lt__(self, /, other: AddedToken) -> bool: ...
    def __ne__(self, /, other: AddedToken) -> bool: ...
    def __new__(cls, /, content: str |None = None, **kwargs) -> AddedToken: ...
    def __repr__(self, /) -> str: ...
    def __setstate__(self, /, state: Any) -> None: ...
    def __str__(self, /) -> str: ...
    @property
    def content(self, /) -> str: ...
    @content.setter
    def content(self, /, content: str) -> None: ...
    @property
    def lstrip(self, /) -> bool: ...
    @property
    def normalized(self, /) -> bool: ...
    @property
    def rstrip(self, /) -> bool: ...
    @property
    def single_word(self, /) -> bool: ...
    @property
    def special(self, /) -> bool: ...
    @special.setter
    def special(self, /, special: bool) -> None: ...

@final
class Encoding:
    def __getstate__(self, /) -> Any: ...
    def __len__(self, /) -> int: ...
    def __new__(cls, /) -> Encoding: ...
    def __repr__(self, /) -> str: ...
    def __setstate__(self, /, state: Any) -> None: ...
    @property
    def attention_mask(self, /) -> list[int]: ...
    def char_to_token(self, /, char_pos: int, sequence_index: int = 0) -> int |None: ...
    def char_to_word(self, /, char_pos: int, sequence_index: int = 0) -> int |None: ...
    @property
    def ids(self, /) -> list[int]: ...
    @staticmethod
    def merge(encodings: Sequence[Encoding], growing_offsets: bool = True) -> "Encoding": ...
    @property
    def n_sequences(self, /) -> int: ...
    @property
    def offsets(self, /) -> list[tuple[int, int]]: ...
    @property
    def overflowing(self, /) -> list[Encoding]: ...
    def pad(self, /, length: int, **kwargs) -> "None": ...
    @property
    def sequence_ids(self, /) -> list[int |None]: ...
    def set_sequence_id(self, /, sequence_id: int) -> None: ...
    @property
    def special_tokens_mask(self, /) -> list[int]: ...
    def token_to_chars(self, /, token_index: int) -> tuple[int, int] |None: ...
    def token_to_sequence(self, /, token_index: int) -> int |None: ...
    def token_to_word(self, /, token_index: int) -> int |None: ...
    @property
    def tokens(self, /) -> list[str]: ...
    def truncate(self, /, max_length: int, stride: int = 0, direction: str = "right") -> "None": ...
    @property
    def type_ids(self, /) -> list[int]: ...
    @property
    def word_ids(self, /) -> list[int |None]: ...
    def word_to_chars(self, /, word_index: int, sequence_index: int = 0) -> tuple[int, int] |None: ...
    def word_to_tokens(self, /, word_index: int, sequence_index: int = 0) -> tuple[int, int] |None: ...
    @property
    def words(self, /) -> list[int |None]: ...

@final
class NormalizedString:
    def __getitem__(self, /, range: int |tuple[int, int] |slice) -> NormalizedString |None: ...
    def __new__(cls, /, sequence: str) -> NormalizedString: ...
    def __repr__(self, /) -> str: ...
    def __str__(self, /) -> str: ...
    def append(self, /, s: str) -> None: ...
    def clear(self, /) -> None: ...
    def filter(self, /, func: Any) -> None: ...
    def for_each(self, /, func: Any) -> None: ...
    def lowercase(self, /) -> None: ...
    def lstrip(self, /) -> None: ...
    def map(self, /, func: Any) -> None: ...
    def nfc(self, /) -> None: ...
    def nfd(self, /) -> None: ...
    def nfkc(self, /) -> None: ...
    def nfkd(self, /) -> None: ...
    @property
    def normalized(self, /) -> str: ...
    @property
    def original(self, /) -> str: ...
    def prepend(self, /, s: str) -> None: ...
    def replace(self, /, pattern: str |Regex, content: str) -> None: ...
    def rstrip(self, /) -> None: ...
    def slice(self, /, range: int |tuple[int, int] |slice) -> NormalizedString |None: ...
    def split(self, /, pattern: str |Regex, behavior: Incomplete) -> list[NormalizedString]: ...
    def strip(self, /) -> None: ...
    def uppercase(self, /) -> None: ...

@final
class PreTokenizedString:
    def __new__(cls, /, s: str) -> PreTokenizedString: ...
    def get_splits(self, /, offset_referential: Incomplete = ..., offset_type: Incomplete = ...) -> list[tuple[str, tuple[int, int], list[Token] |None]]: ...
    def normalize(self, /, func: Any) -> None: ...
    def split(self, /, func: Any) -> None: ...
    def to_encoding(self, /, type_id: int = 0, word_idx: int |None = None) -> "Encoding": ...
    def tokenize(self, /, func: Any) -> None: ...

@final
class Regex:
    def __new__(cls, /, s: str) -> Regex: ...

@final
class Token:
    def __new__(cls, /, id: int, value: str, offsets: tuple[int, int]) -> Token: ...
    def as_tuple(self, /) -> tuple[int, str, tuple[int, int]]: ...
    @property
    def id(self, /) -> int: ...
    @property
    def offsets(self, /) -> tuple[int, int]: ...
    @property
    def value(self, /) -> str: ...

@final
class Tokenizer:
    def __getnewargs__(self, /) -> tuple: ...
    def __getstate__(self, /) -> Any: ...
    def __new__(cls, /, model: Model) -> Tokenizer: ...
    def __repr__(self, /) -> str: ...
    def __setstate__(self, /, state: Any) -> None: ...
    def __str__(self, /) -> str: ...
    def add_special_tokens(self, /, tokens: list) -> int: ...
    def add_tokens(self, /, tokens: list) -> int: ...
    def async_decode_batch(self, /, sequences: Sequence[Sequence[int]], skip_special_tokens: bool = True) -> Any: ...
    def async_encode(self, /, sequence: Any, pair: Any |None = None, is_pretokenized: bool = False, add_special_tokens: bool = True) -> Any: ...
    def async_encode_batch(self, /, input: Sequence[Any], is_pretokenized: bool = False, add_special_tokens: bool = True) -> Any: ...
    def async_encode_batch_fast(self, /, input: Sequence[Any], is_pretokenized: bool = False, add_special_tokens: bool = True) -> Any: ...
    def decode(self, /, ids: Sequence[int], skip_special_tokens: bool = True) -> "str": ...
    def decode_batch(self, /, sequences: Sequence[Sequence[int]], skip_special_tokens: bool = True) -> "list[str]": ...
    @property
    def decoder(self, /) -> Any: ...
    @decoder.setter
    def decoder(self, /, decoder: Decoder |None) -> None: ...
    def enable_padding(self, /, **kwargs) -> "None": ...
    def enable_truncation(self, /, max_length: int, **kwargs) -> "None": ...
    def encode(self, /, sequence: Any, pair: Any |None = None, is_pretokenized: bool = False, add_special_tokens: bool = True) -> "Encoding": ...
    def encode_batch(self, /, input: Sequence[Any], is_pretokenized: bool = False, add_special_tokens: bool = True) -> "list[Encoding]": ...
    def encode_batch_fast(self, /, input: Sequence[Any], is_pretokenized: bool = False, add_special_tokens: bool = True) -> "list[Encoding]": ...
    @property
    def encode_special_tokens(self, /) -> bool: ...
    @encode_special_tokens.setter
    def encode_special_tokens(self, /, value: bool) -> None: ...
    @staticmethod
    def from_buffer(buffer: bytes) -> "Tokenizer": ...
    @staticmethod
    def from_file(path: str) -> "Tokenizer": ...
    @staticmethod
    def from_pretrained(identifier: str, revision: str = ..., token: str |None = None) -> "Tokenizer": ...
    @staticmethod
    def from_str(json: str) -> "Tokenizer": ...
    def get_added_tokens_decoder(self, /) -> "dict[int, AddedToken]": ...
    def get_vocab(self, /, with_added_tokens: bool = True) -> "dict[str, int]": ...
    def get_vocab_size(self, /, with_added_tokens: bool = True) -> "int": ...
    def id_to_token(self, /, id: int) -> "str | None": ...
    @property
    def model(self, /) -> Any: ...
    @model.setter
    def model(self, /, model: Model) -> None: ...
    def no_padding(self, /) -> None: ...
    def no_truncation(self, /) -> None: ...
    @property
    def normalizer(self, /) -> Any: ...
    @normalizer.setter
    def normalizer(self, /, normalizer: Normalizer |None) -> None: ...
    def num_special_tokens_to_add(self, /, is_pair: bool) -> int: ...
    @property
    def padding(self, /) -> dict |None: ...
    def post_process(self, /, encoding: Encoding, pair: Encoding |None = None, add_special_tokens: bool = True) -> Encoding: ...
    @property
    def post_processor(self, /) -> Any: ...
    @post_processor.setter
    def post_processor(self, /, processor: PostProcessor |None) -> None: ...
    @property
    def pre_tokenizer(self, /) -> Any: ...
    @pre_tokenizer.setter
    def pre_tokenizer(self, /, pretok: PreTokenizer |None) -> None: ...
    def save(self, /, path: str, pretty: bool = True) -> "None": ...
    def to_str(self, /, pretty: bool = False) -> "str": ...
    def token_to_id(self, /, token: str) -> "int | None": ...
    def train(self, /, files: Sequence[str], trainer: Trainer |None = None) -> None: ...
    def train_from_iterator(self, /, iterator: Any, trainer: Trainer |None = None, length: int |None = None) -> None: ...
    @property
    def truncation(self, /) -> dict |None: ...

def __getattr__(name: str) -> Incomplete: ...
