from collections.abc import Sequence
from tokenizers import Token
from typing import Any, final

@final
class BPE(Model):
    def __new__(cls, /, vocab: dict[str, int] |str |None = None, merges: Sequence[tuple[str, str]] |str |None = None, **kwargs) -> BPE: ...
    def _clear_cache(self, /) -> "None": ...
    def _resize_cache(self, /, capacity: int) -> "None": ...
    @property
    def byte_fallback(self, /) -> bool: ...
    @byte_fallback.setter
    def byte_fallback(self, /, byte_fallback: bool) -> None: ...
    @property
    def continuing_subword_prefix(self, /) -> str |None: ...
    @continuing_subword_prefix.setter
    def continuing_subword_prefix(self, /, continuing_subword_prefix: str |None) -> None: ...
    @property
    def dropout(self, /) -> float |None: ...
    @dropout.setter
    def dropout(self, /, dropout: float |None) -> None: ...
    @property
    def end_of_word_suffix(self, /) -> str |None: ...
    @end_of_word_suffix.setter
    def end_of_word_suffix(self, /, end_of_word_suffix: str |None) -> None: ...
    @classmethod
    def from_file(cls, /, vocab: str, merges: str, **kwargs) -> "BPE": ...
    @property
    def fuse_unk(self, /) -> bool: ...
    @fuse_unk.setter
    def fuse_unk(self, /, fuse_unk: bool) -> None: ...
    @property
    def ignore_merges(self, /) -> bool: ...
    @ignore_merges.setter
    def ignore_merges(self, /, ignore_merges: bool) -> None: ...
    @staticmethod
    def read_file(vocab: str, merges: str) -> tuple[dict[str, int], list[tuple[str, str]]]: ...
    @property
    def unk_token(self, /) -> str |None: ...
    @unk_token.setter
    def unk_token(self, /, unk_token: str |None) -> None: ...

class Model:
    def __getstate__(self, /) -> Any: ...
    def __new__(cls, /) -> "Model": ...
    def __repr__(self, /) -> str: ...
    def __setstate__(self, /, state: Any) -> None: ...
    def __str__(self, /) -> str: ...
    def get_trainer(self, /) -> Any: ...
    def id_to_token(self, /, id: int) -> str |None: ...
    def save(self, /, folder: str, prefix: str |None = None, name: str |None = None) -> "list[str]": ...
    def token_to_id(self, /, token: str) -> int |None: ...
    def tokenize(self, /, sequence: str) -> list[Token]: ...

@final
class Unigram(Model):
    def __new__(cls, /, vocab: Sequence[tuple[str, float]] |None = None, unk_id: int |None = None, byte_fallback: bool |None = None, alpha: float |None = None, nbest_size: int |None = None) -> Unigram: ...
    def _clear_cache(self, /) -> "None": ...
    def _resize_cache(self, /, capacity: int) -> "None": ...
    @property
    def alpha(self, /) -> float |None: ...
    @alpha.setter
    def alpha(self, /, alpha: float |None) -> None: ...
    @property
    def nbest_size(self, /) -> int |None: ...
    @nbest_size.setter
    def nbest_size(self, /, nbest_size: int |None) -> None: ...

@final
class WordLevel(Model):
    def __new__(cls, /, vocab: dict[str, int] |str |None = None, unk_token: str |None = None) -> WordLevel: ...
    @classmethod
    def from_file(cls, /, vocab: str, unk_token: str |None = None) -> "WordLevel": ...
    @staticmethod
    def read_file(vocab: str) -> dict[str, int]: ...
    @property
    def unk_token(self, /) -> str: ...
    @unk_token.setter
    def unk_token(self, /, unk_token: str) -> None: ...

@final
class WordPiece(Model):
    def __new__(cls, /, vocab: dict[str, int] |str |None = None, **kwargs) -> WordPiece: ...
    @property
    def continuing_subword_prefix(self, /) -> str: ...
    @continuing_subword_prefix.setter
    def continuing_subword_prefix(self, /, continuing_subword_prefix: str) -> None: ...
    @classmethod
    def from_file(cls, /, vocab: str, **kwargs) -> "WordPiece": ...
    @property
    def max_input_chars_per_word(self, /) -> int: ...
    @max_input_chars_per_word.setter
    def max_input_chars_per_word(self, /, max: int) -> None: ...
    @staticmethod
    def read_file(vocab: str) -> dict[str, int]: ...
    @property
    def unk_token(self, /) -> str: ...
    @unk_token.setter
    def unk_token(self, /, unk_token: str) -> None: ...
