import tokenizers
import tokenizers.normalizers
import typing

class BertNormalizer:
    def __new__(
        cls,
        /,
        clean_text: bool = True,
        handle_chinese_chars: bool = True,
        strip_accents: bool | None = None,
        lowercase: bool = True,
    ) -> None: ...
    @property
    def clean_text(self, /) -> bool: ...
    @clean_text.setter
    def clean_text(self, /, clean_text: bool) -> None: ...
    @property
    def handle_chinese_chars(self, /) -> bool: ...
    @handle_chinese_chars.setter
    def handle_chinese_chars(self, /, handle_chinese_chars: bool) -> None: ...
    @property
    def lowercase(self, /) -> bool: ...
    @lowercase.setter
    def lowercase(self, /, lowercase: bool) -> None: ...
    @property
    def strip_accents(self, /) -> typing.Any: ...
    @strip_accents.setter
    def strip_accents(self, /, strip_accents: bool | None) -> None: ...

class ByteLevel:
    def __new__(cls, /) -> None: ...

class Lowercase:
    def __new__(cls, /) -> None: ...

class NFC:
    def __new__(cls, /) -> None: ...

class NFD:
    def __new__(cls, /) -> None: ...

class NFKC:
    def __new__(cls, /) -> None: ...

class NFKD:
    def __new__(cls, /) -> None: ...

class Nmt:
    def __new__(cls, /) -> None: ...

class Normalizer:
    def __getstate__(self, /) -> typing.Any: ...
    def __repr__(self, /) -> str: ...
    def __setstate__(self, /, state: typing.Any) -> typing.Any: ...
    def __str__(self, /) -> str: ...
    @staticmethod
    def custom(obj: typing.Any) -> tokenizers.normalizers.Normalizer: ...
    def normalize(
        self, /, normalized: tokenizers.NormalizedString | tokenizers.NormalizedStringRefMut
    ) -> typing.Any: ...
    def normalize_str(self, /, sequence: str) -> str: ...

class Precompiled:
    def __new__(cls, /, precompiled_charsmap: typing.Any) -> None: ...

class Prepend:
    def __new__(cls, /, prepend: str = ...) -> None: ...
    @property
    def prepend(self, /) -> str: ...
    @prepend.setter
    def prepend(self, /, prepend: str) -> None: ...

class Replace:
    def __new__(cls, /, pattern: str | tokenizers.Regex, content: str) -> None: ...
    @property
    def content(self, /) -> str: ...
    @content.setter
    def content(self, /, content: str) -> None: ...
    @property
    def pattern(self, /) -> typing.Any: ...
    @pattern.setter
    def pattern(self, /, _pattern: str | tokenizers.Regex) -> typing.Any: ...

class Sequence:
    def __getitem__(self, /, index: int) -> typing.Any: ...
    def __getnewargs__(self, /) -> typing.Any: ...
    def __len__(self, /) -> int: ...
    def __new__(cls, /, normalizers: typing.Any) -> None: ...
    def __setitem__(self, /, index: int, value: typing.Any) -> typing.Any: ...

class Strip:
    def __new__(cls, /, left: bool = True, right: bool = True) -> None: ...
    @property
    def left(self, /) -> bool: ...
    @left.setter
    def left(self, /, left: bool) -> None: ...
    @property
    def right(self, /) -> bool: ...
    @right.setter
    def right(self, /, right: bool) -> None: ...

class StripAccents:
    def __new__(cls, /) -> None: ...
