from collections.abc import Sequence as Sequence2
from tokenizers import NormalizedString, Regex
from typing import Any, final

@final
class BertNormalizer(Normalizer):
    def __new__(cls, /, clean_text: bool = True, handle_chinese_chars: bool = True, strip_accents: bool |None = None, lowercase: bool = True) -> BertNormalizer: ...
    @property
    def clean_text(self, /) -> bool: ...
    @clean_text.setter
    def clean_text(self, /, clean_text: bool) -> None: ...
    @property
    def handle_chinese_chars(self, /) -> bool: ...
    @handle_chinese_chars.setter
    def handle_chinese_chars(self, /, handle_chinese_chars: bool) -> None: ...
    @property
    def lowercase(self, /) -> bool: ...
    @lowercase.setter
    def lowercase(self, /, lowercase: bool) -> None: ...
    @property
    def strip_accents(self, /) -> bool |None: ...
    @strip_accents.setter
    def strip_accents(self, /, strip_accents: bool |None) -> None: ...

@final
class ByteLevel(Normalizer):
    def __new__(cls, /) -> ByteLevel: ...

@final
class Lowercase(Normalizer):
    def __new__(cls, /) -> Lowercase: ...

@final
class NFC(Normalizer):
    def __new__(cls, /) -> NFC: ...

@final
class NFD(Normalizer):
    def __new__(cls, /) -> NFD: ...

@final
class NFKC(Normalizer):
    def __new__(cls, /) -> NFKC: ...

@final
class NFKD(Normalizer):
    def __new__(cls, /) -> NFKD: ...

@final
class Nmt(Normalizer):
    def __new__(cls, /) -> Nmt: ...

class Normalizer:
    def __getstate__(self, /) -> Any: ...
    def __repr__(self, /) -> str: ...
    def __setstate__(self, /, state: Any) -> None: ...
    def __str__(self, /) -> str: ...
    @staticmethod
    def custom(obj: Any) -> Normalizer: ...
    def normalize(self, /, normalized: NormalizedString |Any) -> None: ...
    def normalize_str(self, /, sequence: str) -> str: ...

@final
class Precompiled(Normalizer):
    def __new__(cls, /, precompiled_charsmap: Sequence2[int]) -> Precompiled: ...

@final
class Prepend(Normalizer):
    def __new__(cls, /, prepend: str = ...) -> Prepend: ...
    @property
    def prepend(self, /) -> str: ...
    @prepend.setter
    def prepend(self, /, prepend: str) -> None: ...

@final
class Replace(Normalizer):
    def __new__(cls, /, pattern: str |Regex, content: str) -> Replace: ...
    @property
    def content(self, /) -> str: ...
    @content.setter
    def content(self, /, content: str) -> None: ...
    @property
    def pattern(self, /) -> None: ...
    @pattern.setter
    def pattern(self, /, _pattern: str |Regex) -> None: ...

@final
class Sequence(Normalizer):
    def __getitem__(self, /, index: int) -> Any: ...
    def __getnewargs__(self, /) -> tuple: ...
    def __len__(self, /) -> int: ...
    def __new__(cls, /, normalizers: list) -> Sequence: ...
    def __setitem__(self, /, index: int, value: Any) -> None: ...

@final
class Strip(Normalizer):
    def __new__(cls, /, left: bool = True, right: bool = True) -> Strip: ...
    @property
    def left(self, /) -> bool: ...
    @left.setter
    def left(self, /, left: bool) -> None: ...
    @property
    def right(self, /) -> bool: ...
    @right.setter
    def right(self, /, right: bool) -> None: ...

@final
class StripAccents(Normalizer):
    def __new__(cls, /) -> StripAccents: ...
