from _typeshed import Incomplete
from tokenizers import PreTokenizedString, Regex
from typing import Any, final

@final
class BertPreTokenizer(PreTokenizer):
    def __new__(cls, /) -> BertPreTokenizer: ...

@final
class ByteLevel(PreTokenizer):
    def __new__(cls, /, add_prefix_space: bool = True, trim_offsets: bool = True, use_regex: bool = True, **_kwargs) -> ByteLevel: ...
    @property
    def add_prefix_space(self, /) -> bool: ...
    @add_prefix_space.setter
    def add_prefix_space(self, /, add_prefix_space: bool) -> None: ...
    @staticmethod
    def alphabet() -> list[str]: ...
    @property
    def trim_offsets(self, /) -> bool: ...
    @trim_offsets.setter
    def trim_offsets(self, /, trim_offsets: bool) -> None: ...
    @property
    def use_regex(self, /) -> bool: ...
    @use_regex.setter
    def use_regex(self, /, use_regex: bool) -> None: ...

@final
class CharDelimiterSplit(PreTokenizer):
    def __getnewargs__(self, /) -> tuple: ...
    def __new__(cls, /, delimiter: str) -> CharDelimiterSplit: ...
    @property
    def delimiter(self, /) -> str: ...
    @delimiter.setter
    def delimiter(self, /, delimiter: str) -> None: ...

@final
class Digits(PreTokenizer):
    def __new__(cls, /, individual_digits: bool = False) -> Digits: ...
    @property
    def individual_digits(self, /) -> bool: ...
    @individual_digits.setter
    def individual_digits(self, /, individual_digits: bool) -> None: ...

@final
class FixedLength(PreTokenizer):
    def __new__(cls, /, length: int = 5) -> FixedLength: ...
    @property
    def length(self, /) -> int: ...
    @length.setter
    def length(self, /, length: int) -> None: ...

@final
class Metaspace(PreTokenizer):
    def __new__(cls, /, replacement: str = "▁", prepend_scheme: str = ..., split: bool = True) -> Metaspace: ...
    @property
    def prepend_scheme(self, /) -> str: ...
    @prepend_scheme.setter
    def prepend_scheme(self, /, prepend_scheme: str) -> None: ...
    @property
    def replacement(self, /) -> str: ...
    @replacement.setter
    def replacement(self, /, replacement: str) -> None: ...
    @property
    def split(self, /) -> bool: ...
    @split.setter
    def split(self, /, split: bool) -> None: ...

class PreTokenizer:
    def __getstate__(self, /) -> Any: ...
    def __repr__(self, /) -> str: ...
    def __setstate__(self, /, state: Any) -> None: ...
    def __str__(self, /) -> str: ...
    @staticmethod
    def custom(pretok: Any) -> PreTokenizer: ...
    def pre_tokenize(self, /, pretok: PreTokenizedString) -> None: ...
    def pre_tokenize_str(self, /, s: str) -> list[tuple[str, tuple[int, int]]]: ...

@final
class Punctuation(PreTokenizer):
    def __new__(cls, /, behavior: Incomplete = ...) -> Punctuation: ...
    @property
    def behavior(self, /) -> str: ...
    @behavior.setter
    def behavior(self, /, behavior: str) -> None: ...

@final
class Sequence(PreTokenizer):
    def __getitem__(self, /, index: int) -> Any: ...
    def __getnewargs__(self, /) -> tuple: ...
    def __new__(cls, /, pre_tokenizers: list) -> Sequence: ...
    def __setitem__(self, /, index: int, value: Any) -> None: ...

@final
class Split(PreTokenizer):
    def __getnewargs__(self, /) -> tuple: ...
    def __new__(cls, /, pattern: str |Regex, behavior: Incomplete, invert: bool = False) -> Split: ...
    @property
    def behavior(self, /) -> str: ...
    @behavior.setter
    def behavior(self, /, behavior: str) -> None: ...
    @property
    def invert(self, /) -> bool: ...
    @invert.setter
    def invert(self, /, invert: bool) -> None: ...
    @property
    def pattern(self, /) -> None: ...
    @pattern.setter
    def pattern(self, /, _pattern: str |Regex) -> None: ...

@final
class UnicodeScripts(PreTokenizer):
    def __new__(cls, /) -> UnicodeScripts: ...

@final
class Whitespace(PreTokenizer):
    def __new__(cls, /) -> Whitespace: ...

@final
class WhitespaceSplit(PreTokenizer):
    def __new__(cls, /) -> WhitespaceSplit: ...
