from _typeshed import Incomplete
from collections.abc import Sequence as Sequence2
from tokenizers import Encoding
from typing import Any, final

@final
class BertProcessing(PostProcessor):
    def __getnewargs__(self, /) -> tuple: ...
    def __new__(cls, /, sep: tuple[str, int], cls_token: tuple[str, int]) -> BertProcessing: ...
    @property
    def cls(self, /) -> tuple: ...
    @cls.setter
    def cls(self, /, cls: tuple) -> None: ...
    @property
    def sep(self, /) -> tuple: ...
    @sep.setter
    def sep(self, /, sep: tuple) -> None: ...

@final
class ByteLevel(PostProcessor):
    def __new__(cls, /, add_prefix_space: bool |None = None, trim_offsets: bool |None = None, use_regex: bool |None = None, **_kwargs) -> ByteLevel: ...
    @property
    def add_prefix_space(self, /) -> bool: ...
    @add_prefix_space.setter
    def add_prefix_space(self, /, add_prefix_space: bool) -> None: ...
    @property
    def trim_offsets(self, /) -> bool: ...
    @trim_offsets.setter
    def trim_offsets(self, /, trim_offsets: bool) -> None: ...
    @property
    def use_regex(self, /) -> bool: ...
    @use_regex.setter
    def use_regex(self, /, use_regex: bool) -> None: ...

class PostProcessor:
    def __getstate__(self, /) -> Any: ...
    def __repr__(self, /) -> str: ...
    def __setstate__(self, /, state: Any) -> None: ...
    def __str__(self, /) -> str: ...
    def num_special_tokens_to_add(self, /, is_pair: bool) -> int: ...
    def process(self, /, encoding: Encoding, pair: Encoding |None = None, add_special_tokens: bool = True) -> "Encoding": ...

@final
class RobertaProcessing(PostProcessor):
    def __getnewargs__(self, /) -> tuple: ...
    def __new__(cls, /, sep: tuple[str, int], cls_token: tuple[str, int], trim_offsets: bool = True, add_prefix_space: bool = True) -> RobertaProcessing: ...
    @property
    def add_prefix_space(self, /) -> bool: ...
    @add_prefix_space.setter
    def add_prefix_space(self, /, add_prefix_space: bool) -> None: ...
    @property
    def cls(self, /) -> tuple: ...
    @cls.setter
    def cls(self, /, cls: tuple) -> None: ...
    @property
    def sep(self, /) -> tuple: ...
    @sep.setter
    def sep(self, /, sep: tuple) -> None: ...
    @property
    def trim_offsets(self, /) -> bool: ...
    @trim_offsets.setter
    def trim_offsets(self, /, trim_offsets: bool) -> None: ...

@final
class Sequence(PostProcessor):
    def __getitem__(self, /, index: int) -> Any: ...
    def __getnewargs__(self, /) -> tuple: ...
    def __new__(cls, /, processors_py: list) -> Sequence: ...
    def __setitem__(self, /, index: int, value: Any) -> None: ...

@final
class TemplateProcessing(PostProcessor):
    def __new__(cls, /, single: Incomplete |None = None, pair: Incomplete |None = None, special_tokens: Sequence2[Incomplete] |None = None) -> TemplateProcessing: ...
    @property
    def single(self, /) -> str: ...
    @single.setter
    def single(self, /, single: Incomplete) -> None: ...
