import tokenizers
import typing

class BertProcessing:
    def __getnewargs__(self, /) -> typing.Any: ...
    def __new__(cls, /, sep: typing.Any, cls_token: typing.Any) -> None: ...
    @property
    def cls(self, /) -> typing.Any: ...
    @cls.setter
    def cls(self, /, cls: typing.Any) -> typing.Any: ...
    @property
    def sep(self, /) -> typing.Any: ...
    @sep.setter
    def sep(self, /, sep: typing.Any) -> typing.Any: ...

class ByteLevel:
    def __new__(cls, /, add_prefix_space: bool | None = None, trim_offsets: bool | None = None, use_regex: bool | None = None, **_kwargs) -> None: ...
    @property
    def add_prefix_space(self, /) -> bool: ...
    @add_prefix_space.setter
    def add_prefix_space(self, /, add_prefix_space: bool) -> None: ...
    @property
    def trim_offsets(self, /) -> bool: ...
    @trim_offsets.setter
    def trim_offsets(self, /, trim_offsets: bool) -> None: ...
    @property
    def use_regex(self, /) -> bool: ...
    @use_regex.setter
    def use_regex(self, /, use_regex: bool) -> None: ...

class PostProcessor:
    def __getstate__(self, /) -> typing.Any: ...
    def __repr__(self, /) -> str: ...
    def __setstate__(self, /, state: typing.Any) -> typing.Any: ...
    def __str__(self, /) -> str: ...
    def num_special_tokens_to_add(self, /, is_pair: bool) -> int: ...
    def process(self, /, encoding: tokenizers.Encoding, pair: tokenizers.Encoding | None = None, add_special_tokens: bool = True) -> tokenizers.Encoding: ...

class RobertaProcessing:
    def __getnewargs__(self, /) -> typing.Any: ...
    def __new__(cls, /, sep: typing.Any, cls_token: typing.Any, trim_offsets: bool = True, add_prefix_space: bool = True) -> None: ...
    @property
    def add_prefix_space(self, /) -> bool: ...
    @add_prefix_space.setter
    def add_prefix_space(self, /, add_prefix_space: bool) -> None: ...
    @property
    def cls(self, /) -> typing.Any: ...
    @cls.setter
    def cls(self, /, cls: typing.Any) -> typing.Any: ...
    @property
    def sep(self, /) -> typing.Any: ...
    @sep.setter
    def sep(self, /, sep: typing.Any) -> typing.Any: ...
    @property
    def trim_offsets(self, /) -> bool: ...
    @trim_offsets.setter
    def trim_offsets(self, /, trim_offsets: bool) -> None: ...

class Sequence:
    def __getitem__(self, /, index: int) -> typing.Any: ...
    def __getnewargs__(self, /) -> typing.Any: ...
    def __new__(cls, /, processors_py: typing.Any) -> None: ...
    def __setitem__(self, /, index: int, value: typing.Any) -> typing.Any: ...

class TemplateProcessing:
    def __new__(cls, /, single: typing.Any | None = None, pair: typing.Any | None = None, special_tokens: typing.Any | None = None) -> None: ...
    @property
    def single(self, /) -> str: ...
    @single.setter
    def single(self, /, single: typing.Any) -> typing.Any: ...
