from collections.abc import Sequence
from tokenizers import AddedToken
from typing import Any, final

@final
class BpeTrainer(Trainer):
    def __new__(cls, /, **kwargs) -> BpeTrainer: ...
    @property
    def continuing_subword_prefix(self, /) -> str |None: ...
    @continuing_subword_prefix.setter
    def continuing_subword_prefix(self, /, prefix: str |None) -> None: ...
    @property
    def end_of_word_suffix(self, /) -> str |None: ...
    @end_of_word_suffix.setter
    def end_of_word_suffix(self, /, suffix: str |None) -> None: ...
    def get_word_count(self, /) -> int: ...
    @property
    def initial_alphabet(self, /) -> list[str]: ...
    @initial_alphabet.setter
    def initial_alphabet(self, /, alphabet: Sequence[str]) -> None: ...
    @property
    def limit_alphabet(self, /) -> int |None: ...
    @limit_alphabet.setter
    def limit_alphabet(self, /, limit: int |None) -> None: ...
    @property
    def max_token_length(self, /) -> int |None: ...
    @max_token_length.setter
    def max_token_length(self, /, limit: int |None) -> None: ...
    @property
    def min_frequency(self, /) -> int: ...
    @min_frequency.setter
    def min_frequency(self, /, freq: int) -> None: ...
    @property
    def progress_format(self, /) -> str: ...
    @progress_format.setter
    def progress_format(self, /, format: str) -> None: ...
    @property
    def show_progress(self, /) -> bool: ...
    @show_progress.setter
    def show_progress(self, /, show_progress: bool) -> None: ...
    @property
    def special_tokens(self, /) -> list[AddedToken]: ...
    @special_tokens.setter
    def special_tokens(self, /, special_tokens: list) -> None: ...
    @property
    def vocab_size(self, /) -> int: ...
    @vocab_size.setter
    def vocab_size(self, /, vocab_size: int) -> None: ...

class Trainer:
    def __getstate__(self, /) -> Any: ...
    def __repr__(self, /) -> str: ...
    def __setstate__(self, /, state: Any) -> None: ...
    def __str__(self, /) -> str: ...

@final
class UnigramTrainer(Trainer):
    def __new__(cls, /, **kwargs) -> UnigramTrainer: ...
    @property
    def initial_alphabet(self, /) -> list[str]: ...
    @initial_alphabet.setter
    def initial_alphabet(self, /, alphabet: Sequence[str]) -> None: ...
    @property
    def show_progress(self, /) -> bool: ...
    @show_progress.setter
    def show_progress(self, /, show_progress: bool) -> None: ...
    @property
    def special_tokens(self, /) -> list[AddedToken]: ...
    @special_tokens.setter
    def special_tokens(self, /, special_tokens: list) -> None: ...
    @property
    def vocab_size(self, /) -> int: ...
    @vocab_size.setter
    def vocab_size(self, /, vocab_size: int) -> None: ...

@final
class WordLevelTrainer(Trainer):
    def __new__(cls, /, **kwargs) -> WordLevelTrainer: ...
    @property
    def min_frequency(self, /) -> int: ...
    @min_frequency.setter
    def min_frequency(self, /, freq: int) -> None: ...
    @property
    def show_progress(self, /) -> bool: ...
    @show_progress.setter
    def show_progress(self, /, show_progress: bool) -> None: ...
    @property
    def special_tokens(self, /) -> list[AddedToken]: ...
    @special_tokens.setter
    def special_tokens(self, /, special_tokens: list) -> None: ...
    @property
    def vocab_size(self, /) -> int: ...
    @vocab_size.setter
    def vocab_size(self, /, vocab_size: int) -> None: ...

@final
class WordPieceTrainer(Trainer):
    def __new__(cls, /, **kwargs) -> WordPieceTrainer: ...
    @property
    def continuing_subword_prefix(self, /) -> str |None: ...
    @continuing_subword_prefix.setter
    def continuing_subword_prefix(self, /, prefix: str |None) -> None: ...
    @property
    def end_of_word_suffix(self, /) -> str |None: ...
    @end_of_word_suffix.setter
    def end_of_word_suffix(self, /, suffix: str |None) -> None: ...
    @property
    def initial_alphabet(self, /) -> list[str]: ...
    @initial_alphabet.setter
    def initial_alphabet(self, /, alphabet: Sequence[str]) -> None: ...
    @property
    def limit_alphabet(self, /) -> int |None: ...
    @limit_alphabet.setter
    def limit_alphabet(self, /, limit: int |None) -> None: ...
    @property
    def min_frequency(self, /) -> int: ...
    @min_frequency.setter
    def min_frequency(self, /, freq: int) -> None: ...
    @property
    def show_progress(self, /) -> bool: ...
    @show_progress.setter
    def show_progress(self, /, show_progress: bool) -> None: ...
    @property
    def special_tokens(self, /) -> list[AddedToken]: ...
    @special_tokens.setter
    def special_tokens(self, /, special_tokens: list) -> None: ...
    @property
    def vocab_size(self, /) -> int: ...
    @vocab_size.setter
    def vocab_size(self, /, vocab_size: int) -> None: ...
