import typing

class BpeTrainer:
    def __new__(cls, /, **kwargs) -> None:
        """Create and return a new object.  See help(type) for accurate signature."""
        ...
    @property
    def continuing_subword_prefix(self, /) -> typing.Any: ...
    @continuing_subword_prefix.setter
    def continuing_subword_prefix(self, /, prefix: str | None) -> None: ...
    @property
    def end_of_word_suffix(self, /) -> typing.Any: ...
    @end_of_word_suffix.setter
    def end_of_word_suffix(self, /, suffix: str | None) -> None: ...
    @property
    def initial_alphabet(self, /) -> typing.Any: ...
    @initial_alphabet.setter
    def initial_alphabet(self, /, alphabet: typing.Any) -> None: ...
    @property
    def limit_alphabet(self, /) -> typing.Any: ...
    @limit_alphabet.setter
    def limit_alphabet(self, /, limit: int | None) -> None: ...
    @property
    def max_token_length(self, /) -> typing.Any: ...
    @max_token_length.setter
    def max_token_length(self, /, limit: int | None) -> None: ...
    @property
    def min_frequency(self, /) -> int: ...
    @min_frequency.setter
    def min_frequency(self, /, freq: int) -> None: ...
    @property
    def show_progress(self, /) -> bool: ...
    @show_progress.setter
    def show_progress(self, /, show_progress: bool) -> None: ...
    @property
    def special_tokens(self, /) -> typing.Any: ...
    @special_tokens.setter
    def special_tokens(self, /, special_tokens: typing.Any) -> typing.Any: ...
    @property
    def vocab_size(self, /) -> int: ...
    @vocab_size.setter
    def vocab_size(self, /, vocab_size: int) -> None: ...

class Trainer:
    def __getstate__(self, /) -> typing.Any: ...
    def __repr__(self, /) -> str:
        """Return repr(self)."""
        ...
    def __setstate__(self, /, state: typing.Any) -> typing.Any: ...
    def __str__(self, /) -> str:
        """Return str(self)."""
        ...

class UnigramTrainer:
    def __new__(cls, /, **kwargs) -> None:
        """Create and return a new object.  See help(type) for accurate signature."""
        ...
    @property
    def initial_alphabet(self, /) -> typing.Any: ...
    @initial_alphabet.setter
    def initial_alphabet(self, /, alphabet: typing.Any) -> None: ...
    @property
    def show_progress(self, /) -> bool: ...
    @show_progress.setter
    def show_progress(self, /, show_progress: bool) -> None: ...
    @property
    def special_tokens(self, /) -> typing.Any: ...
    @special_tokens.setter
    def special_tokens(self, /, special_tokens: typing.Any) -> typing.Any: ...
    @property
    def vocab_size(self, /) -> int: ...
    @vocab_size.setter
    def vocab_size(self, /, vocab_size: int) -> None: ...

class WordLevelTrainer:
    def __new__(cls, /, **kwargs) -> None:
        """Create and return a new object.  See help(type) for accurate signature."""
        ...
    @property
    def min_frequency(self, /) -> int: ...
    @min_frequency.setter
    def min_frequency(self, /, freq: int) -> None: ...
    @property
    def show_progress(self, /) -> bool: ...
    @show_progress.setter
    def show_progress(self, /, show_progress: bool) -> None: ...
    @property
    def special_tokens(self, /) -> typing.Any: ...
    @special_tokens.setter
    def special_tokens(self, /, special_tokens: typing.Any) -> typing.Any: ...
    @property
    def vocab_size(self, /) -> int: ...
    @vocab_size.setter
    def vocab_size(self, /, vocab_size: int) -> None: ...

class WordPieceTrainer:
    def __new__(cls, /, **kwargs) -> None:
        """Create and return a new object.  See help(type) for accurate signature."""
        ...
    @property
    def continuing_subword_prefix(self, /) -> typing.Any: ...
    @continuing_subword_prefix.setter
    def continuing_subword_prefix(self, /, prefix: str | None) -> None: ...
    @property
    def end_of_word_suffix(self, /) -> typing.Any: ...
    @end_of_word_suffix.setter
    def end_of_word_suffix(self, /, suffix: str | None) -> None: ...
    @property
    def initial_alphabet(self, /) -> typing.Any: ...
    @initial_alphabet.setter
    def initial_alphabet(self, /, alphabet: typing.Any) -> None: ...
    @property
    def limit_alphabet(self, /) -> typing.Any: ...
    @limit_alphabet.setter
    def limit_alphabet(self, /, limit: int | None) -> None: ...
    @property
    def min_frequency(self, /) -> int: ...
    @min_frequency.setter
    def min_frequency(self, /, freq: int) -> None: ...
    @property
    def show_progress(self, /) -> bool: ...
    @show_progress.setter
    def show_progress(self, /, show_progress: bool) -> None: ...
    @property
    def special_tokens(self, /) -> typing.Any: ...
    @special_tokens.setter
    def special_tokens(self, /, special_tokens: typing.Any) -> typing.Any: ...
    @property
    def vocab_size(self, /) -> int: ...
    @vocab_size.setter
    def vocab_size(self, /, vocab_size: int) -> None: ...
