// Generated by cbindgen. DO NOT EDIT.

#ifndef TOKENIZERS_C_H
#define TOKENIZERS_C_H

/* This file is generated by cbindgen from bindings/c/src/lib.rs. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct TkEncoding TkEncoding;

typedef struct TkError TkError;

typedef struct TkTokenizer TkTokenizer;

/**
 * An opaque pointer to a rust-allocated type.
 */
typedef struct TkError *TkHandle_TkError;

/**
 * An opaque pointer to a rust-allocated type.
 */
typedef struct TkTokenizer *TkHandle_TkTokenizer;

/**
 * An opaque pointer to a rust-allocated type.
 */
typedef struct TkEncoding *TkHandle_TkEncoding;

/**
 * A borrowed view into a Rust-owned slice.
 * It's a pointer paired with the slice length.
 * Valid only as long as whatever it points to is still alive.
 */
typedef struct TkSlice_u32 {
  const uint32_t *ptr;
  size_t len;
} TkSlice_u32;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns a pointer to `err`'s message. The pointer is owned by `err` and only valid until `err` is
 * freed with `tk_error_free`.
 *
 * # Safety
 * `err` must be a live pointer returned by a fallible FFI fn, not yet freed with
 * `tk_error_free`.
 */
const char *tk_error_message(const struct TkError *err);

/**
 * Frees an error returned by a fallible FFI fn. Calling this on a NULL pointer is a no-op.
 *
 * # Safety
 * `err` must either be NULL ora live pointer returned by a fallible FFI fn, not yet freed with
 * `tk_error_free`.
 */
void tk_error_free(TkHandle_TkError err);

/**
 * Instantiates a tokenizer from its JSON config file
 *
 * # Safety
 * 1. [`path`] must be non-NULL, point to a NUL-terminated byte string, and be valid for reads
 *    up to and including that NUL byte for the duration of this call. It must not be mutated
 *    while this function runs.
 * 2. [`out`] must be valid, writeable pointer to a [`TkHandle<TkTokenizer>`].
 */
TkHandle_TkError tk_tokenizer_from_file(const char *path, TkHandle_TkTokenizer *out);

/**
 * Frees memory of the TkTokenizer
 *
 * # Safety
 * `handle` must either be NULL or a not-freed-yet [`TkHandle<TkTokenizer>`]
 */
TkHandle_TkError tk_tokenizer_free(TkHandle_TkTokenizer tk_tokenizer);

/**
 * Encodes the input text to tokens using the provided tokenizer.
 *
 * # Safety
 * 1. [`tokenizer`] must be non-NULL and point to a valid, not-yet-freed [`TkHandle<TkTokenizer>`].
 * 2. [`input`] must be non-NULL, point to a NUL-terminated byte string, and be valid for reads
 *    up to and including that NUL byte for the duration of this call. It must not be mutated
 *    while this function runs.
 * 3. [`out`] must be a valid, writeable pointer to a [`TkHandle<TkEncoding>`].
 */
TkHandle_TkError tk_tokenizer_encode(TkHandle_TkTokenizer tk_tokenizer,
                                     const char *input,
                                     bool add_special_tokens,
                                     TkHandle_TkEncoding *out);

/**
 * Frees memory backing the [`TkEncoding`]
 *
 * # Safety
 * `handle` must either be NULL or a not-freed-yet [`TkHandle<TkTokenizer>`]
 */
TkHandle_TkError tk_encoding_free(TkHandle_TkEncoding tk_encoding);

/**
 * Writes `tk_encoding`'s token ids to `out`.
 *
 * # Safety
 * 1. [`tk_encoding`] must be non-NULL and point to a valid, not-yet-freed [`TkHandle<TkEncoding>`].
 * 2. [`out`] must be a valid, writeable pointer to a [`TkSlice<u32>`].
 */
TkHandle_TkError tk_encoding_ids(TkHandle_TkEncoding tk_encoding, struct TkSlice_u32 *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TOKENIZERS_C_H */
