[package]
name = "tokenizers-python"
version = "1.0.0-dev.0"
edition = "2024"
publish = false
authors = [
  "Arthur Zucker <arthur@huggingface.co>",
  "Luc Georges <luc@huggingface.co>",
  "Simon Brandeis <simon@huggingface.co>",
]
[lib]
name = "tokenizers"
crate-type = ["cdylib"]

[dependencies]
# Renamed to tk to avoid collision with the bindings crate name (tokenizers)
tk = { package = "tokenizers", path = "../../tokenizers", features = [
  "train",
  "esaxx_fast",
] }

pyo3 = { version = "=0.29", default-features = false, features = [
  "macros",
  "extension-module",
  "abi3-py310",
  "experimental-inspect",
] }
#TODO: Remove the dependency when we support dlpack
numpy = "=0.29"

[build-dependencies]
pyo3-build-config = "=0.29"

[profile.release]
lto = "fat"
codegen-units = 1
