/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class PipelineTokenizer {
  /**
   * Read a `tokenizer.json`. The file is put through the legacy "1.0" -> canonical "2.0"
   * upgrade first, so the tokenizers already on disk keep loading; `tk_serialize` itself only
   * reads the canonical form.
   */
  static fromFile(path: string): PipelineTokenizer
  /**
   * `Uint32Array`, not `Vec<u32>`: a JS `Array` costs one napi value per token, which on
   * token-dense input is 13x the encode itself (gpt2 chinese 31 vs 616 MB/s).
   */
  encode(text: string, options?: EncodeOptions | undefined | null): Uint32Array
  /**
   * Drops the two remaining per-call costs of [`Self::encode`]: the JS string -> UTF-8 copy
   * (as fast as the tokenizer itself, so it halves throughput) and the fresh `ArrayBuffer`
   * (388 ns of a 789 ns call). Returns how many ids were written.
   */
  encodeBytesInto(text: Uint8Array, out: Uint32Array, options?: EncodeOptions | undefined | null): number
}

/** Per-call settings. A field left out keeps the tokenizer's own behaviour. */
export interface EncodeOptions {
  /**
   * Whether the post-processor adds its special tokens, such as `[CLS]` and `[SEP]`. `true`
   * when left out.
   */
  addSpecialTokens?: boolean
  /**
   * Padding for this call, replacing the tokenizer's configured padding. `false` disables
   * padding. Left out, the configured padding applies.
   */
  padding?: false | PaddingOptions
  /**
   * Truncation for this call, replacing the tokenizer's configured truncation. `false` disables
   * truncation. Left out, the configured truncation applies.
   */
  truncation?: false | TruncationOptions
}

/**
 * Padding for one call. It replaces the tokenizer's configured padding as a whole, so a field
 * left out takes the value noted on the field, not the configured one.
 */
export interface PaddingOptions {
  /**
   * `right` when left out, or `left`: whether padding tokens are appended to the right or
   * prepended to the left of encoded tokens.
   */
  direction?: 'left' | 'right'
  /** The id of the padding token. `0` when left out. */
  padId?: number
  /** The type id of the padding token. `0` when left out. */
  padTypeId?: number
  /** The text of the padding token. `[PAD]` when left out. */
  padToken?: string
  /**
   * Pads every encoding to exactly this many tokens. Left out, pads each batch to its longest
   * item.
   */
  length?: number
  /** Rounds the padded length up to a multiple of this. */
  padToMultipleOf?: number
}

/**
 * Truncation for one call. It replaces the tokenizer's configured truncation as a whole, so a
 * field left out takes the value noted on the field, not the configured one.
 */
export interface TruncationOptions {
  /**
   * The maximum number of tokens, including special tokens, to keep. Encodings with more tokens
   * get truncated.
   */
  maxLength: number
  /**
   * `longest_first` when left out, `only_first` or `only_second`: which sequence of a pair is
   * truncated.
   */
  strategy?: 'longest_first' | 'only_first' | 'only_second'
  /**
   * `right` when left out, or `left`: whether to truncate tokens at the end of the sequence or
   * at its beginning.
   */
  direction?: 'left' | 'right'
}
