name: Delete doc comment

on:
  workflow_run:
    workflows: ["Delete doc comment trigger"]
    types:
      - completed

jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment.yml@90b4ee2c10b81b5c1a6367c4e6fc9e2fb510a7e3  # main
    secrets:
      comment_bot_token: ${{ secrets.COMMENT_BOT_TOKEN }}