name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install sphinx sphinx_rtd_theme setuptools-rust

      - name: Install Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8  # stable

      - name: Build tokenizers
        working-directory: ./bindings/python
        run: pip install -e .

      - name: Build documentation
        working-directory: ./docs
        run: make clean && make html_all O="-W --keep-going"

      - name: Upload built doc
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
        with:
          name: documentation
          path: ./docs/build/*
