name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install sphinx sphinx_rtd_theme setuptools-rust

      - name: Install Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8  # stable

      - name: Build tokenizers
        working-directory: ./bindings/python
        run: pip install -e .

      - name: Build documentation
        working-directory: ./docs
        run: make clean && make html_all O="-W --keep-going"

      - name: Upload built doc
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: documentation
          path: ./docs/build/*
