name: Node
on:
  push:
    branches:
      - main
    paths-ignore:
      - bindings/python/**
  pull_request:
    paths-ignore:
      - bindings/python/**

jobs:
  build_and_test:
    name: Check everything builds & tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bindings/node
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8  # stable

      - name: Cache cargo registry / git / target
        uses: Swatinem/rust-cache@23869a5bd66c73db3c0ac40331f3206eb23791dc  # v2.9.1
        with:
          workspaces: bindings/node

      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
        with:
          node-version: latest

      - name: Install dependencies
        run: yarn install

      - name: Build all
        run: yarn build

      - name: Run JS tests
        run: make test

  quality:
    name: Lint & format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bindings/node
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8  # stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry / git / target
        uses: Swatinem/rust-cache@23869a5bd66c73db3c0ac40331f3206eb23791dc  # v2.9.1
        with:
          workspaces: bindings/node

      - name: Lint with RustFmt
        run: cargo fmt -- --check

      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
        with:
          node-version: latest

      - name: Install dependencies
        run: yarn install

      - name: Lint TS
        run: yarn lint

  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bindings/node
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8  # stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run Audit
        run: cargo audit -D warnings --ignore RUSTSEC-2024-0436 --ignore RUSTSEC-2025-0014 --ignore RUSTSEC-2025-0119